version: '3.5'

networks:
  localdev:
    name: localdev
    
services:
  gateway-api:
    image: isunulswami/gateway-api
    container_name: gateway-api
    restart: always
    ports:
      - "7000:80"
    depends_on:
      - eureka-server
      - config-server
      - customer-api
      - account-api
      - transaction-api
      - request-api
    networks:
      - localdev

   customer-api:
    image: isunulswami/customer-api
    container_name: customer-api
    restart: always
    ports:
      - "7002:80"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - localdev
   
   account-api:
    image: isunulswami/account-api
    container_name: account-api
    restart: always
    ports:
      - "7001:80"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - localdev

   transaction-api:
    image: isunulswami/transaction-api
    container_name: transaction-api
    restart: always
    ports:
      - "7004:80"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - localdev

   request-api:
    image: isunulswami/request-api
    container_name: request-api
    restart: always
    ports:
      - "7003:80"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - localdev
        
  eureka-server:
    image: isunulswami/eureka-server
    container_name: eureka-server
   restart: always
    ports:
      - "8761:80"

  config-server:
    image: isunulswami/eureka-server
    container_name: config-server
   restart: always
    ports:
      - "8888:80"
  
